# Generated by Django 3.0.3 on 2020-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='usuario_photos'),
        ),
    ]
