# Generated by Django 3.0.3 on 2020-03-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0003_usuario_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
