# Generated by Django 3.0.3 on 2020-03-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0007_indicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicado_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='indicado',
            name='valor_comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='indicado',
            name='valor_cotacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(upload_to='usuario_photos'),
        ),
        migrations.AddField(
            model_name='indicado',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jovem.Indicado_status'),
        ),
    ]
