# Generated by Django 3.0.3 on 2020-03-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0009_auto_20200315_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicado',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
