# Generated by Django 3.0.3 on 2020-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0011_auto_20200315_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
