# Generated by Django 3.0.3 on 2020-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0013_textos_tipotexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
    ]
