# Generated by Django 3.0.3 on 2020-04-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0014_auto_20200410_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textos',
            name='texto',
            field=models.TextField(),
        ),
    ]
